name: hp3ki
description: Flutter Template

publish_to: 'none'

version: 1.3.4+9

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  barcode_widget: ^2.0.4
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_file_dialog: ^3.0.2
  flutter_localizations:
    sdk: flutter
  geolocator: ^9.0.1
  get_it: ^7.6.7
  multi_image_picker_plus: ^0.0.4
  pull_to_refresh_flutter3: ^2.0.2

dependency_overrides:
  # wakelock_windows: any
  # win32: any

dev_dependencies:
  android_intent_plus: ^3.1.5
  awesome_dialog: ^3.0.2

  #B
  badges: ^2.0.3
  bottom_picker: ^2.0.1
  bubble_tab_indicator: ^0.1.6
  build_runner: ^2.4.4
  carousel_indicator: ^1.0.6
  carousel_slider: ^4.1.1
  chewie: ^1.5.0

  #C
  chips_choice_null_safety: ^2.0.6
  circular_countdown_timer: ^0.2.3
  currency_text_input_formatter: ^2.1.8
  date_time_picker:
    git:
      url: https://github.com/DavidHDJ/date_time_picker.git
      ref: 2.1.1
  delayed_display: ^2.0.0
  dio: ^4.0.6
  dotted_border: ^2.0.0+3

  #D
  dropdown_search: ^4.0.0
  #device_preview:
  # git:
  #  url: https://github.com/bradrushworth/flutter_device_preview.git
  # path: device_preview
  #E
  equatable: ^2.0.5
  expandable: ^5.0.1
  external_path: ^1.0.1
  file_picker: ^5.3.2
  filesize: ^2.0.1
  firebase_auth: ^4.5.0

  # Firebase & Login providers
  firebase_core: ^2.11.0
  firebase_crashlytics: ^3.3.5
  firebase_messaging: ^14.4.0
  flutter_animated_dialog: ^2.0.1
  flutter_chat_types: ^3.3.4

  #F
  flutter_glow: ^0.3.0
  flutter_html: ^3.0.0-alpha.5
  flutter_launcher_icons: "^0.11.0"
  flutter_link_previewer: ^2.6.6
  flutter_lints: ^1.0.4
  flutter_mentions: ^2.0.1
  flutter_local_notifications: ^9.2.0
  flutter_native_contact_picker: ^0.0.4
  flutter_native_image: ^0.0.6+1
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.0.3
  flutter_switch: ^0.3.2
  flutter_test:
    sdk: flutter
  fluttertoast: ^8.1.1
  gallery_saver: ^2.3.2
  geocoding: ^2.0.5

  #G
  google_api_headers: ^1.3.0
  google_maps_flutter: ^2.2.1
  google_maps_place_picker_mb: ^2.0.0-mb.22
  google_sign_in: ^6.1.0
  hex: ^0.2.0

  #H
  http: ^0.13.5
  http_mock_adapter: ^0.3.3
  image_cropper: ^1.4.1
  image_picker: ^1.0.4

  #I
  intl: ^0.18.0

  #L
  lecle_flutter_absolute_path: ^0.0.2+1
  localization: ^2.1.0
  mask_text_input_formatter: ^2.4.0
  mime: ^1.0.2
  mockito: ^5.0.8

  #M
  modal_bottom_sheet: ^2.0.1

  #N
  new_version_plus: ^0.0.1+4
  package_info_plus: ^4.0.1
  permission_handler: ^10.2.0
  photo_view: ^0.14.0

  #P
  pin_code_fields: ^7.4.0
  provider: ^6.0.4

  #Q
  qr_flutter: ^4.1.0

  #R
  readmore: ^2.2.0
  responsive_framework: ^0.2.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  simple_animations: ^5.0.0+3
  slide_to_confirm: ^1.1.0
  sliding_up_panel: ^2.0.0+1
  sliver_tools: ^0.2.8
  sn_progress_dialog: ^1.0.8

  #S
  soundpool: ^2.3.0
  table_calendar: ^3.0.8

  #T
  tap_debouncer: ^2.0.2
  timeago: ^3.3.0
  timeline_list: ^0.0.6
  timelines: ^0.1.0
  tuple: ^2.0.1
  url_launcher: ^6.1.6

  #U
  uuid: ^3.0.7

  #V
  video_compress: ^3.1.1
  video_player: ^2.6.1

  #W
  webview_flutter: ^3.0.4

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/sounds/
    - assets/language/
    - assets/images/
    - assets/imagesv2/
    - assets/images/auth/
    - assets/images/avatar/
    - assets/images/background/
    - assets/images/bottomsheet/
    - assets/images/logo/
    - assets/images/home/
    - assets/images/icons/
    - assets/images/profile/
    - assets/images/onboarding/
    - assets/images/sos/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
        - asset: assets/fonts/inter/Inter-Bold.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
