name: hp3ki
description: Community App.

publish_to: 'none'

version: 1.4.4+10

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dependency_overrides:
  # wakelock_windows: any
  # win32: any
  intl: 

dev_dependencies:

  # A
  awesome_dialog: ^3.0.2

  # B
  barcode_widget: ^2.0.4
  bottom_picker: ^2.0.1
  bubble_tab_indicator: ^0.1.6

  # C
  cached_network_image: ^3.3.1
  circular_countdown_timer: ^0.2.3
  currency_text_input_formatter: ^2.1.8
  carousel_indicator: ^1.0.6
  carousel_slider: 5.0.0 
  chewie: ^1.7.5
  chips_choice: ^3.0.1

  # D
  dropdown_search: ^6.0.1 
  date_count_down: ^3.0.0
  #device_preview:
  # git:
  #  url: https://github.com/bradrushworth/flutter_device_preview.git
  # path: device_preview
  detectable_text_field: ^3.0.2
  date_time_picker:
    git:
      url: https://github.com/DavidHDJ/date_time_picker.git
      ref: 2.1.1
  delayed_display: ^2.0.0
  dio: ^4.0.6
  device_preview: ^1.2.0
  dotted_border: ^2.0.0+3

  # E
  equatable: ^2.0.5
  expandable: ^5.0.1
  external_path: ^1.0.1

  # Firebase & Login providers
  firebase_core: ^3.0.0
  firebase_auth: ^5.2.0
  firebase_messaging: ^15.2.3

  # F
  flutter_glow: ^0.3.0
  flutter_chat_types: ^3.3.4
  flutter_widget_from_html: 
  flutter_launcher_icons: ^0.14.3
  flutter_link_previewer: ^3.2.2
  flutter_lints: ^1.0.4
  flutter_file_dialog: ^3.0.2
  file_picker: ^5.3.2
  filesize: ^2.0.1
  flutter_typeahead: ^4.3.7
  flutter_local_notifications: ^17.2.3
  flutter_native_contact_picker: ^0.0.4
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.0.3
  fluttertagger: ^2.1.1
  flutter_switch: ^0.3.2
  flutter_test:
    sdk: flutter
  fluttertoast: ^8.1.1
  flutter_google_maps_webservices: ^1.1.1

  # G
  gallery_saver_plus: ^3.1.1
  google_api_headers: ^2.0.0
  google_maps_flutter: ^2.2.1
  google_maps_place_picker_mb: ^3.1.2
  google_sign_in: ^6.1.0
  geocoding: ^2.0.5
  geolocator: ^10.1.0
  get_it: ^7.6.7

  # H
  hex: ^0.2.0

  # I
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+2

  # L
  lecle_flutter_absolute_path: ^0.0.2+1
  localization: ^2.1.0

  # M
  modal_bottom_sheet: ^2.0.1
  multi_image_picker_plus: ^0.0.4
  mask_text_input_formatter: ^2.4.0
  mime: ^1.0.2

  # N
  new_version_plus: ^0.0.1+4

  # P
  package_info_plus: ^4.0.1
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  pin_code_fields: ^8.0.1
  provider: ^6.0.4

  # Q
  qr_flutter: ^4.1.0

  # R
  readmore: ^2.2.0
  responsive_framework: ^0.2.0

  # S
  soundpool: ^2.3.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  simple_animations: ^5.0.0+3
  slide_to_confirm: ^1.1.0
  sliding_up_panel: ^2.0.0+1
  sliver_tools: ^0.2.8
  sn_progress_dialog: ^1.0.8

  # T
  table_calendar: ^3.0.8
  timeago: ^3.3.0
  timelines: ^0.1.0
  tuple: ^2.0.1

  # U
  uuid: ^4.0.0
  url_launcher: ^6.1.6

  # V
  video_compress: ^3.1.3
  video_player: ^2.9.2
  visibility_detector: ^0.4.0+2

  # W
  webview_flutter: ^3.0.4

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/sounds/
    - assets/language/
    - assets/images/
    - assets/imagesv2/
    - assets/images/auth/
    - assets/images/avatar/
    - assets/images/background/
    - assets/images/bottomsheet/
    - assets/images/logo/
    - assets/images/home/
    - assets/images/icons/
    - assets/images/profile/
    - assets/images/onboarding/
    - assets/images/sos/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
        - asset: assets/fonts/inter/Inter-Bold.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
